(define a 1)
(define b 2)
(equal? a a)
(equal? a b)
(equal? 1 1)
(equal? 'a 'b)
(equal? 'a 'a)
(equal? #t #t)
(equal? #t #f)
(equal? #f #t)
(equal? #f #f)
(equal? 1 2)
(equal? #\a #\b)
(equal? #\a #\a)
(equal? 'abc 'aaa)
(equal? 'abc 'abc)
(equal? "" "")
(equal? "1" "")
(equal? "123" "123")
(equal? "123" "1234")
(equal? '(1 2 3 3) '(1 2 3 3))
(equal? '(1 1 3 3) '(1 2 3 3))
(equal? '(1 2 3) '(1 2 3 3))
(equal? '(1) '(1))
(equal? '#(2 2) '#(2 1))
(equal? (lambda(x)1) (lambda(x)1) )
(define a (lambda(x)1))
(define b (lambda(x)2))
(equal? a a)
(equal? a b)